INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Conceição Evaristo', 'conceicao@gmail.com', 'pequenos', 3500.0, '2006-09-20');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Erica Queiroz Pinto', 'erica@gmail.com', 'grandes', 4500.0, '2008-10-23');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Ana Luiza Borges', 'analuiza@gmail.com', 'pequenos', 4200.0, '2005-03-15');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Carlos Eduardo Melo', 'carlosemelo@gmail.com', 'grandes', 5100.0, '1988-07-22');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Fernanda Oliveira', 'fernanda.oliveira@gmail.com', 'silvestres', 3800.0, '2001-11-05');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Roberto Nascimento', 'roberto.nasc@gmail.com', 'pequenos', 4700.0, '1992-04-18');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Juliana Martins', 'julianamartins@gmail.com', 'exóticos', 4000.0, '1998-09-30');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Marcos Vinicius Souza', 'marcos.vinicius@gmail.com', 'grandes', 5500.0, '1985-12-01');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Patricia Lima', 'patricia.lima@gmail.com', 'pequenos', 3900.0, '2003-06-14');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Lucas Ferreira', 'lucas.ferreira@gmail.com', 'silvestres', 4300.0, '2000-02-28');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Camila Rocha', 'camila.rocha@gmail.com', 'exóticos', 4600.0, '1997-08-19');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Diego Almeida', 'diego.almeida@gmail.com', 'pequenos', 3700.0, '2002-01-07');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Tatiane Costa', 'tatiane.costa@gmail.com', 'grandes', 5200.0, '1990-05-23');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Bruno Henrique Dias', 'brunohdias@gmail.com', 'silvestres', 4100.0, '1993-10-11');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Aline Cardoso', 'aline.cardoso@gmail.com', 'pequenos', 3600.0, '2027-03-20');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Felipe Monteiro', 'felipe.monteiro@gmail.com', 'exóticos', 4800.0, '2028-07-15');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Renata Pereira', 'renata.pereira@gmail.com', 'grandes', 5300.0, '1991-02-14');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Anderson Cavalcante', 'anderson.cavalcante@gmail.com', 'pequenos', 4400.0, '1996-11-28');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Vanessa Ribeiro', 'vanessa.ribeiro@gmail.com', 'silvestres', 3950.0, '2004-04-02');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Rafael Azevedo', 'rafael.azevedo@gmail.com', 'pequenos', 4050.0, '1999-07-17');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Isabela Cunha', 'isabela.cunha@gmail.com', 'exóticos', 4900.0, '2029-01-10');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Thiago Barbosa', 'thiago.barbosa@gmail.com', 'grandes', 5000.0, '1987-06-05');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Larissa Pinto', 'larissa.pinto@gmail.com', 'pequenos', 3750.0, '2001-09-22');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Eduardo Gomes', 'edu.gomes@gmail.com', 'silvestres', 4250.0, '1994-03-08');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Natalia Freitas', 'natalia.freitas@gmail.com', 'grandes', 5400.0, '2030-08-25');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Guilherme Santos', 'guilherme.santos@gmail.com', 'exóticos', 4150.0, '1989-12-19');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Priscila Teixeira', 'priscila.teixeira@gmail.com', 'pequenos', 3850.0, '2002-05-31');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Marcelo Duarte', 'marcelo.duarte@gmail.com', 'grandes', 5600.0, '1986-10-14');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Bianca Mendes', 'bianca.mendes@gmail.com', 'silvestres', 4350.0, '2031-02-07');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Rodrigo Vieira', 'rodrigo.vieira@gmail.com', 'pequenos', 4500.0, '1993-08-26');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Simone Lopes', 'simone.lopes@gmail.com', 'exóticos', 3650.0, '2032-11-03');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Alexandre Correia', 'alexandre.correia@gmail.com', 'grandes', 5150.0, '1991-07-09');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Leticia Moreira', 'leticia.moreira@gmail.com', 'pequenos', 3550.0, '2033-04-18');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Henrique Campos', 'henrique.campos@gmail.com', 'silvestres', 4650.0, '1998-01-25');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Debora Fonseca', 'debora.fonseca@gmail.com', 'exóticos', 4750.0, '2034-09-12');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Leonardo Ramos', 'leonardo.ramos@gmail.com', 'grandes', 5250.0, '1995-06-30');
INSERT INTO tb_veterinario (nome, email, especialidade, salario, data_nascimento) VALUES('Amanda Xavier', 'amanda.xavier@gmail.com', 'pequenos', 4000.0, '2000-12-05');