INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Conceição Evaristo', 'conceicao@gmail.com', 'pequenos', 3500.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Erica Queiroz Pinto', 'erica@gmail.com', 'grandes', 4500.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Ana Luiza Borges', 'analuiza@gmail.com', 'pequenos', 4200.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Carlos Eduardo Melo', 'carlosemelo@gmail.com', 'grandes', 5100.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Fernanda Oliveira', 'fernanda.oliveira@gmail.com', 'silvestres', 3800.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Roberto Nascimento', 'roberto.nasc@gmail.com', 'pequenos', 4700.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Juliana Martins', 'julianamartins@gmail.com', 'exóticos', 4000.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Marcos Vinicius Souza', 'marcos.vinicius@gmail.com', 'grandes', 5500.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Patricia Lima', 'patricia.lima@gmail.com', 'pequenos', 3900.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Lucas Ferreira', 'lucas.ferreira@gmail.com', 'silvestres', 4300.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Camila Rocha', 'camila.rocha@gmail.com', 'exóticos', 4600.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Diego Almeida', 'diego.almeida@gmail.com', 'pequenos', 3700.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Tatiane Costa', 'tatiane.costa@gmail.com', 'grandes', 5200.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Bruno Henrique Dias', 'brunohdias@gmail.com', 'silvestres', 4100.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Aline Cardoso', 'aline.cardoso@gmail.com', 'pequenos', 3600.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Felipe Monteiro', 'felipe.monteiro@gmail.com', 'exóticos', 4800.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Renata Pereira', 'renata.pereira@gmail.com', 'grandes', 5300.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Anderson Cavalcante', 'anderson.cavalcante@gmail.com', 'pequenos', 4400.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Vanessa Ribeiro', 'vanessa.ribeiro@gmail.com', 'silvestres', 3950.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Rafael Azevedo', 'rafael.azevedo@gmail.com', 'pequenos', 4050.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Isabela Cunha', 'isabela.cunha@gmail.com', 'exóticos', 4900.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Thiago Barbosa', 'thiago.barbosa@gmail.com', 'grandes', 5000.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Larissa Pinto', 'larissa.pinto@gmail.com', 'pequenos', 3750.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Eduardo Gomes', 'edu.gomes@gmail.com', 'silvestres', 4250.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Natalia Freitas', 'natalia.freitas@gmail.com', 'grandes', 5400.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Guilherme Santos', 'guilherme.santos@gmail.com', 'exóticos', 4150.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Priscila Teixeira', 'priscila.teixeira@gmail.com', 'pequenos', 3850.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Marcelo Duarte', 'marcelo.duarte@gmail.com', 'grandes', 5600.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Bianca Mendes', 'bianca.mendes@gmail.com', 'silvestres', 4350.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Rodrigo Vieira', 'rodrigo.vieira@gmail.com', 'pequenos', 4500.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Simone Lopes', 'simone.lopes@gmail.com', 'exóticos', 3650.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Alexandre Correia', 'alexandre.correia@gmail.com', 'grandes', 5150.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Leticia Moreira', 'leticia.moreira@gmail.com', 'pequenos', 3550.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Henrique Campos', 'henrique.campos@gmail.com', 'silvestres', 4650.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Debora Fonseca', 'debora.fonseca@gmail.com', 'exóticos', 4750.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Leonardo Ramos', 'leonardo.ramos@gmail.com', 'grandes', 5250.0);
INSERT INTO tb_veterinario (nome, email, especialidade, salario) VALUES('Amanda Xavier', 'amanda.xavier@gmail.com', 'pequenos', 4000.0);